### ISSUE TITLE
请问下运行成功后的账号密码是多少呢

### ISSUE THREAD

**Issue by llmoe** [lizhensheng/vue-data-view#1]
如题~感谢

**Comment by lizhensheng** [comment]
看数据库user表



---原始邮件---
发件人: "LLmoe"<notifications@github.com&gt;
发送时间: 2020年3月30日(周一) 下午4:17
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lizhensheng/vue-data-view] 请问下运行成功后的账号密码是多少呢 (#1)




 
如题~感谢

**Comment by lizhensheng** [comment]
最新的数据库文件我今天上传，又修复了一部分问题和功能更新，感谢反馈
