### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by BigCatMiaoMM** [lizhensheng/vue-data-view#2]
后端mongodb 导入文件的时候导入哪个库？

**Comment by lizhensheng** [comment]
库名admin，请在user表下新增一条用户记录，然后可以用你自定义的用户登录了，感谢反馈！

**Comment by lizhensheng** [comment]
也可以导入我提供的user表数据喔。

**Comment by BigCatMiaoMM** [comment]
我全倒入了&nbsp;&nbsp;



---原始邮件---
发件人: "哆啦A梦"<notifications@github.com&gt;
发送时间: 2020年4月3日(周五) 中午11:25
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;;
抄送: "1021030435"<zhouzhengai@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [lizhensheng/vue-data-view] 环境搭建问题 (#2)




 
也可以导入我提供的user表数据喔。

**Comment by BigCatMiaoMM** [comment]
请问 4000端口有什么作用 后端还需要什么环境&nbsp; 我已经mongo导入现在报连不上4000端口的服务 我也不知道那是个什么服务啊- - 牵扯上传吧 我到最后想实现
http://boot.jeecg.com:8080/jeecg-boot/jmreport/bigscreen/index.html?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODU4ODcwOTgsInVzZXJuYW1lIjoiamVlY2cifQ.oaWtAoiv1_Imk9KLKYjLVmgNUlJQ08sRPoDDMpjijJU
这个网址的大屏设计器功能 不知道可以不可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "哆啦A梦"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 中午11:24
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;; 
抄送: "心向光明"<zhouzhengai@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lizhensheng/vue-data-view] 环境搭建问题 (#2)





 
也可以导入我提供的user表数据喔。

**Comment by lizhensheng** [comment]
功能和我的一样，加我qq1841084366 我可以远程给你看一下，你的代码是最新的吗？ 你先更新好代码

**Comment by BigCatMiaoMM** [comment]
嗯 已经加你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "哆啦A梦"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 中午12:06
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;; 
抄送: "心向光明"<zhouzhengai@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lizhensheng/vue-data-view] 环境搭建问题 (#2)





 
功能和我的一样，加我qq1841084366 我可以远程给你看一下，你的代码是最新的吗？ 你先更新好代码

**Comment by benbtx** [comment]
![image](https://user-images.githubusercontent.com/19159482/79420524-a75aa880-7feb-11ea-90bb-51d3a48a0fdd.png)

**Comment by benbtx** [comment]
能贴一个详细配置数据库的图不？（虽然进去了，但把代码也改了，可能是对mongodb 不熟）

**Comment by lizhensheng** [comment]
好的，会写开发文档的，最近不忙的时候就补充的。你可以关注一下



---原始邮件---
发件人: "benbtx"<notifications@github.com&gt;
发送时间: 2020年4月16日(周四) 下午4:35
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"哆啦A梦"<1841084366@qq.com&gt;;
主题: Re: [lizhensheng/vue-data-view] 环境搭建问题 (#2)




 
能贴一个详细配置数据库的图不？（虽然进去了，但把代码也改了，可能是对mongodb 不熟）

**Comment by HenryLin0914** [comment]
請問樓主 mongo 連不上 4000 port的問題
有解決方法嗎
