### ISSUE TITLE
大屏设计

### ISSUE THREAD

**Issue by whj768702** [lizhensheng/vue-data-view#5]
添加了组件以后，拖动不生效呢？看数据，x、y的坐标是改变了的。不知道是哪里出错了

**Comment by whj768702** [comment]
好像是canvas-panel.vue文件中:className="item.uuid === activeElementUUID? 'actived': 'noActived'影响的。具体原因还没找到，等我找到了回来同步下。

**Comment by 1104049235** [comment]
我也拖动不生效  是否解决了？？求助

**Comment by whj768702** [comment]
@1104049235 把className改成classNameActive

**Comment by 1104049235** [comment]
为什么我的linux 系统不能上传图片你的可以吗？

**Comment by 1104049235** [comment]
@whj768702 为什么我发布后连接进入是权限不足！

**Comment by whj768702** [comment]
直接看代码吧，我还没细看。只是本地跑的代码。

**Comment by 1104049235** [comment]
我改好了，多谢





------------------ 原始邮件 ------------------
发件人: whj768702 <notifications@github.com&gt;
发送时间: 2020年7月1日 17:29
收件人: lizhensheng/vue-data-view <vue-data-view@noreply.github.com&gt;
抄送: 1104049235 <1104049235@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[lizhensheng/vue-data-view] 大屏设计 (#5)





 
直接看代码吧，我还没细看。只是本地跑的代码。
