### ISSUE TITLE
您好，mongorestore恢复数据失败好几个集合都有问题

### ISSUE THREAD

**Issue by halloweb** [lizhensheng/vue-data-view#7]
` continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e6748f525e9792d08973d2c') }
2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e67522025d0372650eee607') }
2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e75693df5a6ea46acd55a8b') }
2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5eb2090f6a03136c370e5d2e') }
2020-09-06T21:19:58.908+0800    no indexes to restore`

**Comment by lizhensheng** [comment]
您好，在虚拟机中重装个Monogodb试试


 
---原始邮件---
发件人: "Halloweb"<notifications@github.com&gt;
发送时间: 2020年9月6日 21:30:09
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lizhensheng/vue-data-view] 您好，mongorestore恢复数据失败好几个集合都有问题 (#7)




 
 continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e6748f525e9792d08973d2c') } 2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e67522025d0372650eee607') } 2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5e75693df5a6ea46acd55a8b') } 2020-09-06T21:19:58.907+0800    continuing through error: E11000 duplicate key error collection: admin.groupcomponent index: _id_ dup key: { _id: ObjectId('5eb2090f6a03136c370e5d2e') } 2020-09-06T21:19:58.908+0800    no indexes to restore

**Comment by halloweb** [comment]
没有装虚拟机 安装的window版本  是不是_id这个字段您那定义了没有赋值导致的？键重复。。。

**Comment by lizhensheng** [comment]
估计重复导入数据了，你看有没有创建我定义的表


 
---原始邮件---
发件人: "Halloweb"<notifications@github.com&gt;
发送时间: 2020年9月7日 20:45:30
收件人: "lizhensheng/vue-data-view"<vue-data-view@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"哆啦A梦"<1841084366@qq.com&gt;;
主题: Re: [lizhensheng/vue-data-view] 您好，mongorestore恢复数据失败好几个集合都有问题 (#7)




 
没有装虚拟机 安装的window版本  是不是_id这个字段您那定义了没有赋值导致的？键重复。。。

**Comment by halloweb** [comment]
好了 确实重复创建了  我用的数据库可视化工具没显示数据库我还以为没成功 我命令行进的dbs发现已经存在  谢谢开源
